### ISSUE TITLE
Enum with ranges show up partially red

### ISSUE THREAD

**Issue by mauricelam** [google/pdl-language#6]
The example enum [`CoffeeAddition`](https://github.com/google/pdl/blob/c8479475a1b2d0eb54583d6bf9957f2a45877578/doc/reference.md#enum) in the language reference shows up partially red:

<img width="473" alt="image" src="https://github.com/google/pdl-language/assets/1264702/9dd69653-f611-4745-930b-ce1f46eb76e6">

<details>
<summary>PDL source</summary>

```
enum CoffeeAddition: 5 {
  Empty = 0,

  NonAlcoholic = 1..9 {
    Cream = 1,
    Vanilla = 2,
    Chocolate = 3,
  },

  Alcoholic = 10..19 {
    Whisky = 10,
    Rum = 11,
    Kahlua = 12,
    Aquavit = 13,
  },

  Custom = 20..29,

  Other = ..
}
```
</details>

**Comment by qwandor** [comment]
It looks like the issue is that the `}` after `NonAlcoholic` is ending the enum body, as it doesn't expect nested braces there. Want to send a PR to fix it?

**Comment by mauricelam** [comment]
Uploaded PR #7. That was a good excuse to learn the basics of vscode language extensions

**Comment by qwandor** [comment]
Thanks for the PR! This should now be live in version 0.2.2 in the VSCode marketplace and Open VSX.
